name: flutter_cience
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/exp1.jpg
  - assets/images/exp2.jpg
  - assets/images/background1.png
  - assets/images/background_cinza.png
  - assets/images/cientistas.png
  - assets/images/museus.png
  - assets/images/login.png
  - assets/images/fantastic.png
  - assets/images/favoritos.png
  - assets/images/sp.jpeg
  - assets/images/favoritado.png
  - assets/images/masp.jpg
  - assets/images/museucatavento.jpg
  - assets/images/FRANCIS.png
  - assets/images/acervo.jpg
  - assets/images/acervo1.jpg
  - assets/images/origem.jpg
  - assets/images/OCEANO.jpeg
  - assets/images/museufavelas.jpg
  - assets/images/favelaraiz.jpg
  - assets/images/RAP.jpg
  - assets/images/MAB.jpeg
  - assets/images/historia.jpg
  - assets/images/jardim.jpg